version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.08
    working_directory: ~/repo

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dos2unix
          command: sudo apt-get update && sudo apt-get install -y dos2unix
      - run:
          name: Convert line endings
          command: "find . -type f -print0 | xargs -0 dos2unix"
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - run:
          name: Store APK as an artifact
          command: echo "Storing APK"
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build
