version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.08
    working_directory: ~/repo

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build
