version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Download dependencies
          command: ./gradlew dependencies

      - run:
          name: Run tests
          command: ./gradlew test

      - run:
          name: Build APK
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build