name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install dos2unix
      run: sudo apt-get update && sudo apt-get install -y dos2unix

    - name: Convert line endings
      run: find . -type f -print0 | xargs -0 dos2unix

    - name: Set Gradlew Permissions
      run: chmod +x ./gradlew

    - name: Download dependencies
      run: ./gradlew dependencies

    - name: Run tests
      run: ./gradlew test

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
